"""Render the final markdown report and the plain-text stats table."""

from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path

from .packer import PackResult
from .tokens import backend_name, count_tokens

LANG_BY_EXT = {
    ".py": "python", ".js": "javascript", ".jsx": "jsx", ".ts": "typescript",
    ".tsx": "tsx", ".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin",
    ".rb": "ruby", ".php": "php", ".c": "c", ".h": "c", ".cpp": "cpp",
    ".hpp": "cpp", ".cs": "csharp", ".swift": "swift", ".scala": "scala",
    ".sh": "bash", ".bash": "bash", ".zsh": "bash", ".ps1": "powershell",
    ".sql": "sql", ".lua": "lua", ".html": "html", ".css": "css",
    ".scss": "scss", ".json": "json", ".yaml": "yaml", ".yml": "yaml",
    ".toml": "toml", ".xml": "xml", ".md": "markdown", ".rst": "rst",
    ".txt": "text",
}

LANG_BY_BASENAME = {"dockerfile": "dockerfile", "makefile": "makefile"}


def human_tokens(n: int) -> str:
    if n < 10_000:
        return f"{n:,}"
    return f"{n / 1000:.1f}k"


def _fence(text: str) -> str:
    """Pick a fence longer than any backtick run inside *text*."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    return "`" * max(3, longest + 1)


def _lang_for(relpath: str) -> str:
    base = relpath.rsplit("/", 1)[-1].lower()
    if base in LANG_BY_BASENAME:
        return LANG_BY_BASENAME[base]
    return LANG_BY_EXT.get(os.path.splitext(base)[1], "")


def _build_tree(annotations: dict[str, str]) -> list[str]:
    tree: dict = {}
    for path in sorted(annotations):
        parts = path.split("/")
        node = tree
        for part in parts[:-1]:
            node = node.setdefault((part, True), {})
        node[(parts[-1], False)] = annotations[path]

    lines: list[str] = []

    def walk(node: dict, prefix: str) -> None:
        items = sorted(node.items(), key=lambda kv: (not kv[0][1], kv[0][0]))
        for i, ((name, is_dir), value) in enumerate(items):
            last = i == len(items) - 1
            connector = "└── " if last else "├── "
            if is_dir:
                lines.append(f"{prefix}{connector}{name}/")
                walk(value, prefix + ("    " if last else "│   "))
            else:
                lines.append(f"{prefix}{connector}{name}  {value}")

    walk(tree, "")
    return lines


def render_markdown(result: PackResult, root: Path, generated: datetime | None = None) -> str:
    generated = generated or datetime.now()
    lines: list[str] = []

    pct = (result.used / result.budget * 100) if result.budget else 0.0
    lines.append("# Codebase Pack")
    lines.append("")
    lines.append(f"Generated by [budgetpack](https://github.com/Zhuayu16/budgetpack)"
                 f" - packed *{root.name}* for LLM consumption.")
    lines.append("")
    lines.append(f"- **Source:** `{root.as_posix()}`")
    lines.append(f"- **Generated:** {generated.strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"- **Tokenizer:** {backend_name()}")
    lines.append(
        f"- **Budget:** {result.budget:,} tokens - packed {result.used:,} ({pct:.1f}%)"
    )
    lines.append(
        f"- **Files:** {len(result.packed)} packed, {len(result.omitted)} omitted"
        f" ({result.found_count} found)"
    )
    lines.append("")

    annotations: dict[str, str] = {}
    for p in result.packed:
        mark = "●" if not p.truncated else "◐"
        annotations[p.entry.relpath] = f"{mark} {human_tokens(p.included_tokens)}"
    for om in result.omitted:
        annotations[om.entry.relpath] = f"○ {human_tokens(om.entry.tokens)}"

    lines.append("## Repository tree")
    lines.append("")
    lines.append("● packed · ◐ truncated to fit budget · ○ omitted")
    lines.append("")
    lines.append("```text")
    lines.extend(_build_tree(annotations))
    lines.append("```")
    lines.append("")

    lines.append("## File contents")
    lines.append("")
    for p in result.packed:
        lines.append(f"### {p.entry.relpath}")
        lines.append("")
        meta = f"{p.included_tokens:,} tokens"
        if p.truncated and p.note:
            meta += f" **({p.note})**"
        lines.append(f"*{meta}*")
        lines.append("")
        text = p.entry.text or ""
        fence = _fence(text)
        lang = _lang_for(p.entry.relpath)
        lines.append(f"{fence}{lang}")
        lines.append(text.rstrip("\n"))
        lines.append(fence)
        lines.append("")

    if result.omitted:
        lines.append("## Omitted files")
        lines.append("")
        lines.append("These were found but left out of the pack:")
        lines.append("")
        lines.append("| File | Tokens | Reason |")
        lines.append("|---|---:|---|")
        for om in result.omitted:
            path = om.entry.relpath
            tokens = om.entry.tokens
            lines.append(f"| `{path}` | {human_tokens(tokens)} | {om.reason} |")
        lines.append("")

    return "\n".join(lines)


def render_stats(rows: list[tuple[str, int, float, str]], total: int, top: int) -> str:
    """Render `budgetpack stats`: (relpath, tokens, score, top reason) rows."""
    lines: list[str] = []
    lines.append(f"{'TOKENS':>9}  {'SHARE':>6}  {'SCORE':>6}  REASON / FILE")
    lines.append("-" * 72)
    for relpath, tokens, score, reason in rows[:top]:
        share = (tokens / total * 100) if total else 0.0
        lines.append(f"{human_tokens(tokens):>9}  {share:5.1f}%  {score:6.0f}  {reason}")
        lines.append(f"{'':>9}  {'':>6}  {'':>6}  {relpath}")
    lines.append("-" * 72)
    lines.append(f"{human_tokens(total):>9}  {'100%':>6}           total across all files")
    return "\n".join(lines)


def total_output_tokens(text: str) -> int:
    return count_tokens(text)
